name: calorie_tracker_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  flutter_riverpod: ^2.6.1
  path: ^1.9.1
  get_it: ^8.0.3
  flutter_native_splash: ^2.4.6
  shared_preferences: ^2.1.1
  intl: ^0.20.2
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  provider: ^6.1.5
  cached_network_image: ^3.4.1
  test_cov_console: ^0.2.2
  mockito: ^5.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/apple_juice.png
    - assets/images/cornflake.jpg
    - assets/images/logo.png
    - .env

flutter_native_splash:
  color: "#4CAF50"
  image: assets/images/logo.png
  branding: assets/images/branding.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: assets/images/android_logo.png
    icon_background_color: "#4CAF50"
    branding: assets/images/branding.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
